# TOML document to test conversion feature.

boolean = true
date_time = 1984-12-09T04:30:00
floating_point = 3.14
infinite_float = -inf
nan_float = nan
integer = 42
string = "I'm a string"
array = [ "val1", "val2", "val3" ]
